import {
  EpeverKeyMappedAddresses,
  EpeverKeyMappedFunctionCodeNames,
  EpeverNumberKeyTableOperationType,
} from '../types';

export const EPEVER_KEY_MAPPED_DATA: EpeverKeyMappedAddresses = {
  A1: {
    variableName: 'Over temperature inside the device',
    databaseColumnName: 'overTemperatureInsideTheDevice',
    functionOperationTypes: 'r',
    address: '2000',
    functionCode: '02',
    description:
      '1 The temperature inside the controller is higher than the over-temperature protection point. 0 Normal',
  },
  A2: {
    variableName: 'Day/Night',
    databaseColumnName: 'isNight',
    functionOperationTypes: 'r',
    address: '200C',
    functionCode: '02',
    description: '1-Night, 0-Day',
  },
  A3: {
    variableName: 'PV array input voltage',
    databaseColumnName: 'PVArrayInputVoltage',
    functionOperationTypes: 'r',
    address: '3100',
    functionCode: '04',
    description: 'Solar charge controller--PV array voltage',
    unit: 'VOLT',
    times: 100,
  },
  A4: {
    variableName: 'PV array input current',
    databaseColumnName: 'PVArrayInputCurrent',
    functionOperationTypes: 'r',
    address: '3101',
    functionCode: '04',
    description: 'Solar charge controller--PV array current',
    unit: 'AMPERE',
    times: 100,
  },
  A5: {
    variableName: 'PV array input power L',
    databaseColumnName: 'PVArrayInputPowerL',
    functionOperationTypes: 'r',
    address: '3102',
    functionCode: '04',
    description: 'Solar charge controller--PV array power',
    unit: 'WATT',
    times: 100,
  },
  A6: {
    variableName: 'PV array input power H',
    databaseColumnName: 'PVArrayInputPowerH',
    functionOperationTypes: 'r',
    address: '3103',
    functionCode: '04',
    description: 'Solar charge controller--PV array power',
    unit: 'WATT',
    times: 100,
  },
  A7: {
    variableName: 'Load voltage',
    databaseColumnName: 'loadVoltage',
    functionOperationTypes: 'r',
    address: '310C',
    functionCode: '04',
    description: 'Load voltage',
    unit: 'VOLT',
    times: 100,
  },
  A8: {
    variableName: 'Load current',
    databaseColumnName: 'loadCurrent',
    functionOperationTypes: 'r',
    address: '310D',
    functionCode: '04',
    description: 'Load current',
    unit: 'AMPERE',
    times: 100,
  },
  A9: {
    variableName: 'Load power L',
    databaseColumnName: 'loadPowerL',
    functionOperationTypes: 'r',
    address: '310E',
    functionCode: '04',
    description: 'Load power',
    unit: 'WATT',
    times: 100,
  },
  A10: {
    variableName: 'Load power H',
    databaseColumnName: 'loadPowerH',
    functionOperationTypes: 'r',
    address: '310F',
    functionCode: '04',
    description: 'Load power',
    unit: 'WATT',
    times: 100,
  },
  A11: {
    variableName: 'Battery temperature',
    databaseColumnName: 'batteryTemperature',
    functionOperationTypes: 'r',
    address: '3110',
    functionCode: '04',
    description: 'Battery temperature',
    unit: 'CELSIUS',
    times: 100,
  },
  A12: {
    variableName: 'Device temperature',
    databaseColumnName: 'deviceTemperature',
    functionOperationTypes: 'r',
    address: '3111',
    functionCode: '04',
    description: 'Device temperature',
    unit: 'CELSIUS',
    times: 100,
  },
  A13: {
    variableName: 'Battery SOC',
    databaseColumnName: 'batterySOC',
    functionOperationTypes: 'r',
    address: '311A',
    functionCode: '04',
    description: "The percentage of battery's remaining capacity",
    unit: 'PERCENTAGE',
    times: 1,
  },
  A14: {
    variableName: "Battery's real rated voltage",
    databaseColumnName: 'batteryRealRatedVoltage',
    functionOperationTypes: 'r',
    address: '311D',
    functionCode: '04',
    description:
      'Current system rated voltage. 1200, 2400, 3600, 4800 represent 12V, 24V, 36V, 48V',
    unit: 'VOLT',
    times: 100,
  },
  A15: {
    variableName: 'Battery status',
    databaseColumnName: 'batteryStatus',
    functionOperationTypes: 'r',
    address: '3200',
    functionCode: '04',
    description:
      'D15: 1-Wrong identification for rated voltage D8: Battery inner resistance abnormal 1, normal 0 D7-D4: 00H Normal, 01H Over Temp.(Higher than the warning settings), 02H Low Temp.(Lower than the warning settings), D3-D0: 00H Normal ,01H Over Voltage. , 02H Under Voltage, 03H Over discharge, 04H Fault',
  },
  A16: {
    variableName: 'Charging equipment status',
    databaseColumnName: 'chargingEquipmentStatus',
    functionOperationTypes: 'r',
    address: '3201',
    functionCode: '04',
    description:
      'D15-D14: Input voltage status. 00H normal, 01H No input power connected, 02H Higher input voltage , 03H Input voltage error. D13: Charging MOSFET is short circuit. D12: Charging or Anti-reverse MOSFET is open circuit. D11: Anti-reverse MOSFET is short circuit. D10: Input is over current. D9: The load is over current. D8: The load is short circuit. D7: Load MOSFET is short circuit. D6:Disequilibrium in three circuits.',
  },
  A17: {
    variableName: 'Discharging equipment status',
    databaseColumnName: 'dischargingEquipmentStatus',
    functionOperationTypes: 'r',
    address: '3202',
    functionCode: '04',
    description:
      'D15-D14: 00H Input voltage normal, 01H Input voltage low, 02H Input voltage high, 03H no access. D13-D12: Output power. 00H Light load, 01H Moderate, 02H rated, 03H overload D11: Short circuit D10: Unable to discharge D9: Unable to stop discharging D8: Output voltage abnormal D7: Input over voltage D6: Short circuit in high voltage side D5: Boost over voltage D4: Output over voltage D1: 0 Normal, 1 Fault. D0: 1 Running, 0 Standby.',
  },
  A18: {
    variableName: 'Maximum battery voltage today',
    databaseColumnName: 'maximumBatteryVoltageToday',
    functionOperationTypes: 'r',
    address: '3302',
    functionCode: '04',
    description: '00: 00 Refresh every day',
    unit: 'VOLT',
    times: 100,
  },
  A19: {
    variableName: 'Minimum battery voltage today',
    databaseColumnName: 'minimumBatteryVoltageToday',
    functionOperationTypes: 'r',
    address: '3303',
    functionCode: '04',
    description: '00: 00 Refresh every day',
    unit: 'VOLT',
    times: 100,
  },
  A20: {
    variableName: 'Consumed energy today L',
    databaseColumnName: 'consumedEnergyTodayL',
    functionOperationTypes: 'r',
    address: '3304',
    functionCode: '04',
    description: '00: 00 Clear every day',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A21: {
    variableName: 'Consumed energy today H',
    databaseColumnName: 'consumedEnergyTodayH',
    functionOperationTypes: 'r',
    address: '3305',
    functionCode: '04',
    description: '00: 00 Clear every day',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A22: {
    variableName: 'Consumed energy this month L',
    databaseColumnName: 'consumedEnergyThisMonthL',
    functionOperationTypes: 'r',
    address: '3306',
    functionCode: '04',
    description: '00: 00 Clear on the first day of month',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A23: {
    variableName: 'Consumed energy this month H',
    databaseColumnName: 'consumedEnergyThisMonthH',
    functionOperationTypes: 'r',
    address: '3307',
    functionCode: '04',
    description: '00: 00 Clear on the first day of month',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A24: {
    variableName: 'Consumed energy this year L',
    databaseColumnName: 'consumedEnergyThisYearL',
    functionOperationTypes: 'r',
    address: '3308',
    functionCode: '04',
    description: '00: 00 Clear on 1, Jan',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A25: {
    variableName: 'Consumed energy this year H',
    databaseColumnName: 'consumedEnergyThisYearH',
    functionOperationTypes: 'r',
    address: '3309',
    functionCode: '04',
    description: '00: 00 Clear on 1, Jan',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A26: {
    variableName: 'Total consumed energy L',
    databaseColumnName: 'totalConsumedEnergyL',
    functionOperationTypes: 'r',
    address: '330A',
    functionCode: '04',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A27: {
    variableName: 'Total consumed energy H',
    databaseColumnName: 'totalConsumedEnergyH',
    functionOperationTypes: 'r',
    address: '330B',
    functionCode: '04',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A28: {
    variableName: 'Generated energy today L',
    databaseColumnName: 'generatedEnergyTodayL',
    functionOperationTypes: 'r',
    address: '330C',
    functionCode: '04',
    description: '00: 00 Clear every day.',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A29: {
    variableName: 'Generated energy today H',
    databaseColumnName: 'generatedEnergyTodayH',
    functionOperationTypes: 'r',
    address: '330D',
    functionCode: '04',
    description: '00: 00 Clear every day.',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A30: {
    variableName: 'Generated energy this month L',
    databaseColumnName: 'generatedEnergyThisMonthL',
    functionOperationTypes: 'r',
    address: '330E',
    functionCode: '04',
    description: '00: 00 Clear on the first day of month.',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A31: {
    variableName: 'Generated energy this month H',
    databaseColumnName: 'generatedEnergyThisMonthH',
    functionOperationTypes: 'r',
    address: '330F',
    functionCode: '04',
    description: '00: 00 Clear on the first day of month.',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A32: {
    variableName: 'Generated energy this year L',
    databaseColumnName: 'generatedEnergyThisYearL',
    functionOperationTypes: 'r',
    address: '3310',
    functionCode: '04',
    description: '00: 00 Clear on 1, Jan.',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A33: {
    variableName: 'Generated energy this year H',
    databaseColumnName: 'generatedEnergyThisYearH',
    functionOperationTypes: 'r',
    address: '3311',
    functionCode: '04',
    description: '00: 00 Clear on 1, Jan.',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A34: {
    variableName: 'Total generated energy L',
    databaseColumnName: 'totalGeneratedEnergyL',
    functionOperationTypes: 'r',
    address: '3312',
    functionCode: '04',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A35: {
    variableName: 'Total generated energy H',
    databaseColumnName: 'totalGeneratedEnergyH',
    functionOperationTypes: 'r',
    address: '3313',
    functionCode: '04',
    unit: 'KILOWATT_HOUR',
    times: 100,
  },
  A36: {
    variableName: 'Battery voltage',
    databaseColumnName: 'batteryVoltage',
    functionOperationTypes: 'r',
    address: '331A',
    functionCode: '04',
    description: 'Battery voltage',
    unit: 'VOLT',
    times: 100,
  },
  A37: {
    variableName: 'Battery current L',
    databaseColumnName: 'batteryCurrentL',
    functionOperationTypes: 'r',
    address: '331B',
    functionCode: '04',
    description: 'Battery current',
    unit: 'AMPERE',
    times: 100,
  },
  A38: {
    variableName: 'Battery current H',
    databaseColumnName: 'batteryCurrentH',
    functionOperationTypes: 'r',
    address: '331C',
    functionCode: '04',
    description: 'Battery current',
    unit: 'AMPERE',
    times: 100,
  },
  B1: {
    variableName: 'Rated charging current',
    databaseColumnName: 'ratedChargingCurrent',
    functionOperationTypes: 'r',
    address: '3005',
    functionCode: '04',
    description: 'Rated current to battery',
    unit: 'AMPERE',
    times: 100,
  },
  B2: {
    variableName: 'Rated load current',
    databaseColumnName: 'ratedLoadCurrent',
    functionOperationTypes: 'r',
    address: '300E',
    functionCode: '04',
    description: 'Rated current to load',
    unit: 'AMPERE',
    times: 100,
  },
  B3: {
    variableName: "Battery's real rated voltage",
    databaseColumnName: 'batteryRealRatedVoltage',
    functionOperationTypes: 'r',
    address: '311D',
    functionCode: '04',
    description:
      'Current system rated voltage. 1200, 2400, 3600, 4800 represent 12V, 24V, 36V, 48V',
    unit: 'VOLT',
    times: 100,
  },
  B4: {
    variableName: 'Battery type',
    databaseColumnName: 'batteryType',
    functionOperationTypes: 'rw',
    address: '9000',
    functionCode: ['03', '10'],
    description: '0000H User defined, 0001H Sealed , 0002H GEL, 0003H Flooded,',
  },
  B5: {
    variableName: 'Battery capacity',
    databaseColumnName: 'batteryCapacity',
    functionOperationTypes: 'rw',
    address: '9001',
    functionCode: ['03', '10'],
    description: 'Rated capacity of the battery',
    unit: 'AMPERE_HOUR',
  },
  B6: {
    variableName: 'Temperature compensation coefficient',
    databaseColumnName: 'temperatureCompensationCoefficient',
    functionOperationTypes: 'rw',
    address: '9002',
    functionCode: ['03', '10'],
    description: 'Range 0-9',
    unit: 'MV_C2_2V',
    times: 100,
  },
  B7: {
    variableName: 'Over voltage disconnect voltage',
    databaseColumnName: 'overVoltageDisconnectVoltage',
    functionOperationTypes: 'rw',
    address: '9003',
    functionCode: ['03', '10'],
    unit: 'VOLT',
    times: 100,
  },
  B8: {
    variableName: 'Charging limit voltage',
    databaseColumnName: 'chargingLimitVoltage',
    functionOperationTypes: 'rw',
    address: '9004',
    functionCode: ['03', '10'],
    unit: 'VOLT',
    times: 100,
  },
  B9: {
    variableName: 'Over voltage reconnect voltage',
    databaseColumnName: 'overVoltageReconnectVoltage',
    functionOperationTypes: 'rw',
    address: '9005',
    functionCode: ['03', '10'],
    unit: 'VOLT',
    times: 100,
  },
  B10: {
    variableName: 'Equalize charging voltage',
    databaseColumnName: 'equalizeChargingVoltage',
    functionOperationTypes: 'rw',
    address: '9006',
    functionCode: ['03', '10'],
    unit: 'VOLT',
    times: 100,
  },
  B11: {
    variableName: 'Boost charging voltage',
    databaseColumnName: 'boostChargingVoltage',
    functionOperationTypes: 'rw',
    address: '9007',
    functionCode: ['03', '10'],
    unit: 'VOLT',
    times: 100,
  },
  B12: {
    variableName: 'Float charging voltage',
    databaseColumnName: 'floatChargingVoltage',
    functionOperationTypes: 'rw',
    address: '9008',
    functionCode: ['03', '10'],
    unit: 'VOLT',
    times: 100,
  },
  B13: {
    variableName: 'Boost reconnect charging voltage',
    databaseColumnName: 'boostReconnectChargingVoltage',
    functionOperationTypes: 'rw',
    address: '9009',
    functionCode: ['03', '10'],
    unit: 'VOLT',
    times: 100,
  },
  B14: {
    variableName: 'Low voltage reconnect voltage',
    databaseColumnName: 'lowVoltageReconnectVoltage',
    functionOperationTypes: 'rw',
    address: '900A',
    functionCode: ['03', '10'],
    unit: 'VOLT',
    times: 100,
  },
  B15: {
    variableName: 'Under voltage warning recover voltage',
    databaseColumnName: 'underVoltageWarningRecoverVoltage',
    functionOperationTypes: 'rw',
    address: '900B',
    functionCode: ['03', '10'],
    unit: 'VOLT',
    times: 100,
  },
  B16: {
    variableName: 'Under voltage warning voltage',
    databaseColumnName: 'underVoltageWarningVoltage',
    functionOperationTypes: 'rw',
    address: '900C',
    functionCode: ['03', '10'],
    unit: 'VOLT',
    times: 100,
  },
  B17: {
    variableName: 'Low voltage disconnect voltage',
    databaseColumnName: 'lowVoltageDisconnectVoltage',
    functionOperationTypes: 'rw',
    address: '900D',
    functionCode: ['03', '10'],
    unit: 'VOLT',
    times: 100,
  },
  B18: {
    variableName: 'Discharging limit voltage',
    databaseColumnName: 'dischargingLimitVoltage',
    functionOperationTypes: 'rw',
    address: '900E',
    functionCode: ['03', '10'],
    unit: 'VOLT',
    times: 100,
  },
  B19: {
    variableName: 'Battery rated voltage level',
    databaseColumnName: 'batteryRatedVoltageLevel',
    functionOperationTypes: 'rw',
    address: '9067',
    functionCode: ['03', '10'],
    description:
      '0, auto recognize. 1-12V, 2-24V, 3-36V, 4-48V, 5-60V, 6-110V, 7-120V, 8-220V, 9-240V',
  },
  B20: {
    variableName: 'Default load On/Off in manual mode',
    databaseColumnName: 'defaultLoadOnOffInManualMode',
    functionOperationTypes: 'rw',
    address: '906A',
    functionCode: ['03', '10'],
    description: '0-off, 1-on',
  },
  B21: {
    variableName: 'Equalize duration',
    databaseColumnName: 'equalizeDuration',
    functionOperationTypes: 'rw',
    address: '906B',
    functionCode: ['03', '10'],
    description: 'Usually 60-120 minutes',
    unit: 'MINUTE',
  },
  B22: {
    variableName: 'Boost duration',
    databaseColumnName: 'boostDuration',
    functionOperationTypes: 'rw',
    address: '906C',
    functionCode: ['03', '10'],
    description: 'Usually 60-120 minutes',
    unit: 'MINUTE',
  },
  B23: {
    variableName: 'Battery discharge',
    databaseColumnName: 'batteryDischarge',
    functionOperationTypes: 'rw',
    address: '906D',
    functionCode: ['03', '10'],
    description:
      "Usually 20%-80%. The percentage of battery's remaining capacity when stop charging",
    unit: 'PERCENTAGE',
    times: 100,
  },
  B24: {
    variableName: 'Battery charge',
    databaseColumnName: 'batteryCharge',
    functionOperationTypes: 'rw',
    address: '906E',
    functionCode: ['03', '10'],
    description: 'Depth of charge, 100%',
    unit: 'PERCENTAGE',
    times: 100,
  },
  B25: {
    variableName: 'Charging mode',
    databaseColumnName: 'chargingMode',
    functionOperationTypes: 'rw',
    address: '9070',
    functionCode: ['03', '10'],
    description:
      'Management modes of battery charge and discharge, voltage compensation : 0 and SOC : 1',
  },
  C1: {
    variableName: 'Manual control the load',
    functionOperationTypes: 'w',
    address: '2',
    functionCode: '05',
    description: 'When the load is manual mode, 1-manual on 0 -manual off',
  },
  C2: {
    variableName: 'Night time threshold voltage(NT TV)',
    databaseColumnName: 'nightTimeThresholdVoltageNTTV',
    functionOperationTypes: 'rw',
    address: '901E',
    functionCode: ['03', '10'],
    description:
      'PV voltage is lower than this value, controller would detect it as sundown',
    unit: 'VOLT',
    times: 100,
  },
  C3: {
    variableName: 'Light signal startup (night) delay time',
    databaseColumnName: 'lightSignalStartupNightDelayTime',
    functionOperationTypes: 'rw',
    address: '901F',
    functionCode: ['03', '10'],
    description:
      'PV voltage is lower than NTTV, and duration exceeds the Light signal startup (night) delay time, controller would detect it as night time.',
    unit: 'MINUTE',
  },
  C4: {
    variableName: 'Day time threshold voltage(DT TV)',
    databaseColumnName: 'dayTimeThresholdVoltageDTTV',
    functionOperationTypes: 'rw',
    address: '9020',
    functionCode: ['03', '10'],
    description:
      'PV voltage is higher than this value, controller would detect it as sunrise',
    unit: 'VOLT',
    times: 100,
  },
  C5: {
    variableName: 'Light signal close (day) delay time',
    databaseColumnName: 'lightSignalCloseDayDelayTime',
    functionOperationTypes: 'rw',
    address: '9021',
    functionCode: ['03', '10'],
    description:
      'PV voltage higher than DTTV, and duration exceeds the Light signal close (day) delay time, controller would detect it as day time.',
    unit: 'MINUTE',
  },
  C6: {
    variableName: 'Load control mode',
    databaseColumnName: 'loadControlMode',
    functionOperationTypes: 'rw',
    address: '903D',
    functionCode: ['03', '10'],
    description:
      '0000H Manual Control 0001H Light ON/OFF 0002H Light ON+ Timer/ 0003H Timing Control',
  },
  C7: {
    variableName: 'Light on + time(time1)',
    databaseColumnName: 'LightOnTimeTime1',
    functionOperationTypes: 'rw',
    address: '903E',
    functionCode: ['03', '10'],
    description: 'The length of load output timer1, D15-D8,hour, D7-D0, minute',
  },
  C8: {
    variableName: 'Light on + time(time2)',
    databaseColumnName: 'LightOnTimeTime2',
    functionOperationTypes: 'rw',
    address: '903F',
    functionCode: ['03', '10'],
    description:
      'The length of load output timer2, D15-D8, hour, D7-D0, minute',
  },
  C9: {
    variableName: 'Timing control (turn on time1)',
    databaseColumnName: 'timingControlTurnOnTime1Second',
    functionOperationTypes: 'rw',
    address: '9042',
    functionCode: ['03', '10'],
    description: 'Turn on/off time of load output.',
    unit: 'SECOND',
  },
  C10: {
    variableName: 'Timing control (turn on time1)',
    databaseColumnName: 'timingControlTurnOnTime1Minute',
    functionOperationTypes: 'rw',
    address: '9043',
    functionCode: ['03', '10'],
    description: 'Turn on/off time of load output.',
    unit: 'MINUTE',
  },
  C11: {
    variableName: 'Timing control (turn on time1)',
    databaseColumnName: 'timingControlTurnOnTime1Hour',
    functionOperationTypes: 'rw',
    address: '9044',
    functionCode: ['03', '10'],
    description: 'Turn on/off time of load output.',
    unit: 'HOUR',
  },
  C12: {
    variableName: 'Timing control (turn off time1)',
    databaseColumnName: 'timingControlTurnOffTime1Second',
    functionOperationTypes: 'rw',
    address: '9045',
    functionCode: ['03', '10'],
    description: 'Turn on/off time of load output.',
    unit: 'SECOND',
  },
  C13: {
    variableName: 'Timing control (turn off time1)',
    databaseColumnName: 'timingControlTurnOffTime1Minute',
    functionOperationTypes: 'rw',
    address: '9046',
    functionCode: ['03', '10'],
    description: 'Turn on/off time of load output.',
    unit: 'MINUTE',
  },
  C14: {
    variableName: 'Timing control (turn off time1)',
    databaseColumnName: 'timingControlTurnOffTime1Hour',
    functionOperationTypes: 'rw',
    address: '9047',
    functionCode: ['03', '10'],
    description: 'Turn on/off time of load output.',
    unit: 'HOUR',
  },
  C15: {
    variableName: 'Timing control (turn on time2)',
    databaseColumnName: 'timingControlTurnOnTime2Second',
    functionOperationTypes: 'rw',
    address: '9048',
    functionCode: ['03', '10'],
    description: 'Turn on/off time of load output.',
    unit: 'SECOND',
  },
  C16: {
    variableName: 'Timing control (turn on time2)',
    databaseColumnName: 'timingControlTurnOnTime2Minute',
    functionOperationTypes: 'rw',
    address: '9049',
    functionCode: ['03', '10'],
    description: 'Turn on/off time of load output.',
    unit: 'MINUTE',
  },
  C17: {
    variableName: 'Timing control (turn on time2)',
    databaseColumnName: 'timingControlTurnOnTime2Hour',
    functionOperationTypes: 'rw',
    address: '904A',
    functionCode: ['03', '10'],
    description: 'Turn on/off time of load output.',
    unit: 'HOUR',
  },
  C18: {
    variableName: 'Timing control (turn off time2)',
    databaseColumnName: 'timingControlTurnOffTime2Second',
    functionOperationTypes: 'rw',
    address: '904B',
    functionCode: ['03', '10'],
    description: 'Turn on/off time of load output.',
    unit: 'SECOND',
  },
  C19: {
    variableName: 'Timing control (turn off time2)',
    databaseColumnName: 'timingControlTurnOffTime2Minute',
    functionOperationTypes: 'rw',
    address: '904C',
    functionCode: ['03', '10'],
    description: 'Turn on/off time of load output.',
    unit: 'MINUTE',
  },
  C20: {
    variableName: 'Timing control (turn off time2)',
    databaseColumnName: 'timingControlTurnOffTime2Hour',
    functionOperationTypes: 'rw',
    address: '904D',
    functionCode: ['03', '10'],
    description: 'Turn on/off time of load output.',
    unit: 'HOUR',
  },
  C21: {
    variableName: 'Night time',
    databaseColumnName: 'nightTime',
    functionOperationTypes: 'rw',
    address: '9065',
    functionCode: ['03', '10'],
    description:
      'Set default values of the whole night length of time. D15-D8,hour, D7-D0, minute',
  },
  C22: {
    variableName: 'Timing control (time choose)',
    databaseColumnName: 'timingControlTimeChoose',
    functionOperationTypes: 'rw',
    address: '9069',
    functionCode: ['03', '10'],
    description:
      'Record the time of load. 0，use one time，1-use two times，and so on',
  },
  C23: {
    variableName: 'Default load On/Off in manual mode',
    databaseColumnName: 'defaultLoadOnOffInManualMode',
    functionOperationTypes: 'rw',
    address: '906A',
    functionCode: ['03', '10'],
    description: '0-off，1-on',
  },
  D1: {
    variableName: 'Real time clock',
    databaseColumnName: 'realTimeClockSecondsMinutes',
    functionOperationTypes: 'rw',
    address: '9013',
    functionCode: ['03', '10'],
    description:
      'D7-0 Sec, D15-8Min. (Year, Month, Day, Hour,Min, Sec. should be written simultaneously)',
  },
  D2: {
    variableName: 'Real time clock',
    databaseColumnName: 'realTimeClockHourDay',
    functionOperationTypes: 'rw',
    address: '9014',
    functionCode: ['03', '10'],
    description: 'D7-0 Hour, D15-8 Day',
  },
  D3: {
    variableName: 'Real time clock',
    databaseColumnName: 'realTimeClockMonthYear',
    functionOperationTypes: 'rw',
    address: '9015',
    functionCode: ['03', '10'],
    description: 'D7-0 Month, D15-8 Year',
  },
  E1: {
    variableName: 'Battery upper temperature limit',
    databaseColumnName: 'batteryUpperTemperatureLimit',
    functionOperationTypes: 'rw',
    address: '9017',
    functionCode: ['03', '10'],
    unit: 'CELSIUS',
    times: 100,
  },
  E2: {
    variableName: 'Battery lower temperature limit',
    databaseColumnName: 'batteryLowerTemperatureLimit',
    functionOperationTypes: 'rw',
    address: '9018',
    functionCode: ['03', '10'],
    unit: 'CELSIUS',
    times: 100,
  },
  E3: {
    variableName: 'Device over temperature',
    databaseColumnName: 'deviceOverTemperature',
    functionOperationTypes: 'rw',
    address: '9019',
    functionCode: ['03', '10'],
    unit: 'CELSIUS',
    times: 100,
  },
  E4: {
    variableName: 'Device recovery temperature',
    databaseColumnName: 'deviceRecoveryTemperature',
    functionOperationTypes: 'rw',
    address: '901A',
    functionCode: ['03', '10'],
    unit: 'CELSIUS',
    times: 100,
  },
  E5: {
    variableName: 'Backlight time',
    databaseColumnName: 'backlightTime',
    functionOperationTypes: 'rw',
    address: '9063',
    functionCode: ['03', '10'],
    description:
      'Close after LCD backlight light setting the number of seconds',
    unit: 'CELSIUS',
    times: 100,
  },
  F1: {
    variableName: 'Array rated voltage',
    databaseColumnName: 'arrayRatedVoltage',
    functionOperationTypes: 'r',
    address: '3000',
    functionCode: '04',
    description: 'PV array rated voltage',
    unit: 'VOLT',
    times: 100,
  },
  F2: {
    variableName: 'Array rated current',
    databaseColumnName: 'arrayRatedCurrent',
    functionOperationTypes: 'r',
    address: '3001',
    functionCode: '04',
    description: 'PV array rated current',
    unit: 'AMPERE',
    times: 100,
  },
  F3: {
    variableName: 'Array rated power L',
    databaseColumnName: 'arrayRatedPowerL',
    functionOperationTypes: 'r',
    address: '3002',
    functionCode: '04',
    description: 'PV array rated power (low 16 bits)',
    unit: 'WATT',
    times: 100,
  },
  F4: {
    variableName: 'Array rated power H',
    databaseColumnName: 'arrayRatedPowerH',
    functionOperationTypes: 'r',
    address: '3003',
    functionCode: '04',
    description: 'PV array rated power (high 16 bits)',
    unit: 'WATT',
    times: 100,
  },
  F5: {
    variableName: 'Battery rated voltage',
    databaseColumnName: 'batteryRatedVoltage',
    functionOperationTypes: 'r',
    address: '3004',
    functionCode: '04',
    description: 'Rated voltage to battery',
    unit: 'VOLT',
    times: 100,
  },
  F6: {
    variableName: 'Battery rated current',
    databaseColumnName: 'batteryRatedCurrent',
    functionOperationTypes: 'r',
    address: '3005',
    functionCode: '04',
    description: 'Rated current to battery',
    unit: 'AMPERE',
    times: 100,
  },
  F7: {
    variableName: 'Battery rated power L',
    databaseColumnName: 'batteryRatedPowerL',
    functionOperationTypes: 'r',
    address: '3006',
    functionCode: '04',
    description: 'Rated power to battery(low 16 bits)',
    unit: 'WATT',
    times: 100,
  },
  F8: {
    variableName: 'Battery rated power H',
    databaseColumnName: 'batteryRatedPowerH',
    functionOperationTypes: 'r',
    address: '3007',
    functionCode: '04',
    description: 'Rated power to battery(high 16 bits)',
    unit: 'WATT',
    times: 100,
  },
  F9: {
    variableName: 'Rated load voltage',
    databaseColumnName: 'ratedLoadVoltage',
    functionOperationTypes: 'r',
    address: '300D',
    functionCode: '04',
    description: 'Rated voltage to load',
    unit: 'VOLT',
    times: 100,
  },
  F10: {
    variableName: 'Rated load current',
    databaseColumnName: 'ratedLoadCurrent',
    functionOperationTypes: 'r',
    address: '300E',
    functionCode: '04',
    description: 'Rated current to load',
    unit: 'AMPERE',
    times: 100,
  },
  F11: {
    variableName: 'Rated load power to L',
    databaseColumnName: 'ratedLoadPowerToL',
    functionOperationTypes: 'r',
    address: '300F',
    functionCode: '04',
    description: 'Rated power to load(low 16 bits)',
    unit: 'WATT',
    times: 100,
  },
  F12: {
    variableName: 'Rated load power to H',
    databaseColumnName: 'ratedLoadPowerToH',
    functionOperationTypes: 'r',
    address: '3010',
    functionCode: '04',
    description: 'Rated power to load(high 16 bits)',
    unit: 'WATT',
    times: 100,
  },
  G1: {
    variableName: 'Charging device on/off',
    functionOperationTypes: 'w',
    address: '0',
    functionCode: '05',
    description: '1 Charging device on 0 Charging device off',
  },
  G2: {
    variableName: 'Output control mode manual/automatic',
    functionOperationTypes: 'w',
    address: '1',
    functionCode: '05',
    description: '1 Output control mode manual 0 Output control mode automatic',
  },
  G3: {
    variableName: 'Manual control the load',
    functionOperationTypes: 'w',
    address: '2',
    functionCode: '05',
    description: 'When the load is manual mode, 1-manual on 0 -manual off',
  },
  G4: {
    variableName: 'Default control the load',
    functionOperationTypes: 'w',
    address: '3',
    functionCode: '05',
    description: 'When the load is default mode, 1-manual on 0 -manual off',
  },
  G5: {
    variableName: 'Enable load test mode',
    functionOperationTypes: 'w',
    address: '5',
    functionCode: '05',
    description: '1 Enable 0 Disable(normal)',
  },
  G6: {
    variableName: 'Force the load on/off',
    functionOperationTypes: 'w',
    address: '6',
    functionCode: '05',
    description: '1 Turn on 0 Turn off (used for temporary test of the load）',
  },
  G7: {
    variableName: 'Restore system defaults',
    functionOperationTypes: 'w',
    address: '13',
    functionCode: '05',
    description: '1 yes 0 no',
  },
  G8: {
    variableName: 'Clear generating electricity statistics',
    functionOperationTypes: 'w',
    address: '14',
    functionCode: '05',
    description: '1 clear. Root privileges to perform',
  },
};

export const EPEVER_FUNCTION_CODES_TO_FUNCTION_NAMES: EpeverKeyMappedFunctionCodeNames =
  {
    '02': 'readDiscreteInputs',
    '03': 'readHoldingRegisters',
    '04': 'readInputRegisters',
    '05': 'writeCoil',
    '10': 'writeRegisters',
  };

export const EPEVER_NUMBER_KEY_TABLE_OPERATION_TYPE: EpeverNumberKeyTableOperationType =
  {
    A1: 'r',
    A2: 'r',
    A3: 'r',
    A4: 'r',
    A5: 'r',
    A6: 'r',
    A7: 'r',
    A8: 'r',
    A9: 'r',
    A10: 'r',
    A11: 'r',
    A12: 'r',
    A13: 'r',
    A14: 'r',
    A15: 'r',
    A16: 'r',
    A17: 'r',
    A18: 'r',
    A19: 'r',
    A20: 'r',
    A21: 'r',
    A22: 'r',
    A23: 'r',
    A24: 'r',
    A25: 'r',
    A26: 'r',
    A27: 'r',
    A28: 'r',
    A29: 'r',
    A30: 'r',
    A31: 'r',
    A32: 'r',
    A33: 'r',
    A34: 'r',
    A35: 'r',
    A36: 'r',
    A37: 'r',
    A38: 'r',
    B1: 'r',
    B2: 'r',
    B3: 'r',
    B4: 'rw',
    B5: 'rw',
    B6: 'rw',
    B7: 'rw',
    B8: 'rw',
    B9: 'rw',
    B10: 'rw',
    B11: 'rw',
    B12: 'rw',
    B13: 'rw',
    B14: 'rw',
    B15: 'rw',
    B16: 'rw',
    B17: 'rw',
    B18: 'rw',
    B19: 'rw',
    B20: 'rw',
    B21: 'rw',
    B22: 'rw',
    B23: 'rw',
    B24: 'rw',
    B25: 'rw',
    C1: 'w',
    C2: 'rw',
    C3: 'rw',
    C4: 'rw',
    C5: 'rw',
    C6: 'rw',
    C7: 'rw',
    C8: 'rw',
    C9: 'rw',
    C10: 'rw',
    C11: 'rw',
    C12: 'rw',
    C13: 'rw',
    C14: 'rw',
    C15: 'rw',
    C16: 'rw',
    C17: 'rw',
    C18: 'rw',
    C19: 'rw',
    C20: 'rw',
    C21: 'rw',
    C22: 'rw',
    C23: 'rw',
    D1: 'rw',
    D2: 'rw',
    D3: 'rw',
    E1: 'rw',
    E2: 'rw',
    E3: 'rw',
    E4: 'rw',
    E5: 'rw',
    F1: 'r',
    F2: 'r',
    F3: 'r',
    F4: 'r',
    F5: 'r',
    F6: 'r',
    F7: 'r',
    F8: 'r',
    F9: 'r',
    F10: 'r',
    F11: 'r',
    F12: 'r',
    G1: 'w',
    G2: 'w',
    G3: 'w',
    G4: 'w',
    G5: 'w',
    G6: 'w',
    G7: 'w',
    G8: 'w',
  };

export const EPEVER_BASE_PATH_PORT = '/dev/ttyACM';
