import { GoodweKeyMappedAddresses } from '../types/goodwe';

export const GOODWE_KEY_MAPPED_DATA: GoodweKeyMappedAddresses = {
  A1: {
    address: '0000',
    databaseColumnName: 'lowestFeedingVoltageOfPV',
    functionCode: '03',
    functionOperationTypes: ['r', 'w'],
    times: 10,
    unit: 'VOLT',
    variableName: 'Lowest Feeding Voltage of PV',
  },
  A2: {
    address: '0001',
    databaseColumnName: 'reconnectTime',
    functionCode: '03',
    functionOperationTypes: ['r', 'w'],
    times: 1,
    unit: 'SECOND',
    variableName: 'Reconnect Time',
  },
  A3: {
    address: '0002',
    databaseColumnName: 'highLimitOfGridVoltage',
    functionCode: '03',
    functionOperationTypes: ['r', 'w'],
    times: 10,
    unit: 'VOLT',
    variableName: 'High limit of Grid Voltage',
  },
  A4: {
    address: '0003',
    databaseColumnName: 'lowLimitOfGridVoltage',
    functionCode: '03',
    functionOperationTypes: ['r', 'w'],
    times: 10,
    unit: 'VOLT',
    variableName: 'Low limit of Grid Voltage',
  },
  A5: {
    address: '0004',
    databaseColumnName: 'highLimitOfGridFrequency',
    functionCode: '03',
    functionOperationTypes: ['r', 'w'],
    times: 100,
    unit: 'HERTZ',
    variableName: 'High limit of Grid Frequency',
  },
  A6: {
    address: '0005',
    databaseColumnName: 'lowLimitOfGridFreqency',
    functionCode: '03',
    functionOperationTypes: ['r', 'w'],
    times: 100,
    unit: 'HERTZ',
    variableName: 'Low limit of Grid Freqency',
  },
  A7: {
    address: '0010',
    databaseColumnName: 'rtcDateTimeYearMonth',
    functionCode: '03',
    functionOperationTypes: ['r', 'w'],
    variableName: 'RTC date&time',
  },
  A8: {
    address: '0011',
    databaseColumnName: 'rtcDateTimeDateHour',
    functionCode: '03',
    functionOperationTypes: ['r', 'w'],
    variableName: 'RTC date&time',
  },
  A9: {
    address: '0012',
    databaseColumnName: 'rtcDateTimeMinuteSecond',
    functionCode: '03',
    functionOperationTypes: ['r', 'w'],
    variableName: 'RTC date&time',
  },
  A10: {
    address: '0100',
    databaseColumnName: 'rangeOfRealPowerAdjust',
    functionCode: '05',
    functionOperationTypes: 'w',
    variableName: 'Range of real power adjust',
    description: '0%~100% of rated real power',
    unit: 'PERCENTAGE',
  },
  A11: {
    address: '0101',
    databaseColumnName: 'rangeOfReactivePowerAdjust',
    functionCode: '05',
    functionOperationTypes: 'w',
    variableName: 'Range of reactive power adjust',
    description: '1‐10 as 0.99‐0.9 lagging 90‐100 as leading 0.90‐1',
  },
  A12: {
    address: '0200', // 0200-0207
    databaseColumnName: 'serialNumberOfInverter',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Serial Number Of Inverter',
    description: 'ASCII code, 16 bytes',
  },
  A13: {
    address: '0210', // 0210-0214
    databaseColumnName: 'modelNameOfInverter',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Model Name Of Inverter',
    description: 'ASCII Code, 10 Bytes',
  },
  A14: {
    address: '0220',
    databaseColumnName: 'errorCode',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Error Code',
    description: 'Refer to Error message table',
  },
  A15: {
    address: '0222',
    databaseColumnName: 'eTotal',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'ETotal',
    description: 'Total Energy Yield',
    unit: 'KILOWATT',
    times: 10,
  },
  A16: {
    address: '0224',
    databaseColumnName: 'hTotal',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'HTotal',
    description: 'Total Yield Time',
    unit: 'HOUR',
  },
  A17: {
    address: '0226',
    databaseColumnName: 'pvVoltageOfFirstTracker',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'PV voltage of first tracker',
    unit: 'VOLT',
    times: 10,
  },
  A18: {
    address: '0227',
    databaseColumnName: 'pvVoltageOfSecondTracker',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'PV voltage of second tracker',
    unit: 'VOLT',
    times: 10,
  },
  A19: {
    address: '0228',
    databaseColumnName: 'pvCurrentOfFirstTracker',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'PV current of first tracker',
    unit: 'AMPERE',
    times: 10,
  },
  A20: {
    address: '0229',
    databaseColumnName: 'pvCurrentOfSecondTracker',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'PV current of second tracker',
    unit: 'AMPERE',
    times: 10,
  },
  A21: {
    address: '022A',
    databaseColumnName: 'gridVoltageOfPhase1',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Grid voltage of Phase 1',
    unit: 'VOLT',
    times: 10,
  },
  A22: {
    address: '022B',
    databaseColumnName: 'gridVoltageOfPhase2',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Grid voltage of Phase 2',
    unit: 'VOLT',
    times: 10,
  },
  A23: {
    address: '022C',
    databaseColumnName: 'gridVoltageOfPhase3',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Grid voltage of Phase 3',
    unit: 'VOLT',
    times: 10,
  },
  A24: {
    address: '022D',
    databaseColumnName: 'gridCurrentOfPhase1',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Grid Current of Phase 1',
    unit: 'AMPERE',
    times: 10,
  },
  A25: {
    address: '022E',
    databaseColumnName: 'gridCurrentOfPhase2',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Grid Current of Phase 2',
    unit: 'AMPERE',
    times: 10,
  },
  A26: {
    address: '022F',
    databaseColumnName: 'gridCurrentOfPhase3',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Grid Current of Phase 3',
    unit: 'AMPERE',
    times: 10,
  },
  A27: {
    address: '0230',
    databaseColumnName: 'gridFrequencyOfPhase1',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Grid Frequency of Phase 1',
    unit: 'HERTZ',
    times: 100,
  },
  A28: {
    address: '0231',
    databaseColumnName: 'gridFrequencyOfPhase2',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Grid Frequency of Phase 2',
    unit: 'HERTZ',
    times: 100,
  },
  A29: {
    address: '0232',
    databaseColumnName: 'gridFrequencyOfPhase3',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Grid Frequency of Phase 3',
    unit: 'HERTZ',
    times: 100,
  },
  A30: {
    address: '0233',
    databaseColumnName: 'feedingPowerToGrid',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Feeding power to grid',
    unit: 'WATT',
  },
  A31: {
    address: '0234',
    databaseColumnName: 'runningStatus',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Running status',
    description: '0: cWaitMode 1: cNormalMode 2: cFaultMode',
  },
  A32: {
    address: '0235',
    databaseColumnName: 'temperatureOfHeatsink',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Temperature of Heatsink',
    unit: 'CELSIUS',
    times: 10,
  },
  A33: {
    address: '0236',
    databaseColumnName: 'eYieldDay',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'EDay',
    description: 'Energy yield in current day',
    unit: 'KILOWATT',
    times: 10,
  },
  A34: {
    address: '0300',
    databaseColumnName: 'vpv1',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Vpv1',
    description: 'PV1 voltage',
    unit: 'VOLT',
    times: 10,
  },
  A35: {
    address: '0301',
    databaseColumnName: 'vpv2',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Vpv2',
    description: 'PV2 voltage',
    unit: 'VOLT',
    times: 10,
  },
  A36: {
    address: '0302',
    databaseColumnName: 'ipv1',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Ipv1',
    description: 'PV1 current',
    unit: 'AMPERE',
    times: 10,
  },
  A37: {
    address: '0303',
    databaseColumnName: 'ipv2',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Ipv2',
    description: 'PV2 current',
    unit: 'AMPERE',
    times: 10,
  },
  A38: {
    address: '0304',
    databaseColumnName: 'vac1',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Vac1',
    description: 'Phase L1 voltage',
    unit: 'VOLT',
    times: 10,
  },
  A39: {
    address: '0305',
    databaseColumnName: 'vac2',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Vac2',
    description: 'Phase L2 voltage',
    unit: 'VOLT',
    times: 10,
  },
  A40: {
    address: '0306',
    databaseColumnName: 'vac3',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Vac3',
    description: 'Phase L3 voltage',
    unit: 'VOLT',
    times: 10,
  },
  A41: {
    address: '0307',
    databaseColumnName: 'iac1',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Iac1',
    description: 'Phase L1 current',
    unit: 'AMPERE',
    times: 10,
  },
  A42: {
    address: '0308',
    databaseColumnName: 'iac2',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Iac2',
    description: 'Phase L2 current',
    unit: 'AMPERE',
    times: 10,
  },
  A43: {
    address: '0309',
    databaseColumnName: 'iac3',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Iac3',
    description: 'Phase L3 current',
    unit: 'AMPERE',
    times: 10,
  },
  A44: {
    address: '030A',
    databaseColumnName: 'fac1',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Fac1',
    description: 'Phase L1 frequency',
    unit: 'HERTZ',
    times: 100,
  },
  A45: {
    address: '030B',
    databaseColumnName: 'fac2',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Fac2',
    description: 'Phase L2 frequency',
    unit: 'HERTZ',
    times: 100,
  },
  A46: {
    address: '030C',
    databaseColumnName: 'fac3',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Fac3',
    description: 'Phase L3 frequency',
    unit: 'HERTZ',
    times: 100,
  },
  A47: {
    address: '030D',
    databaseColumnName: 'pacL',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Pac L',
    description: 'low Byte of Feeding power',
    unit: 'WATT',
  },
  A48: {
    address: '030E',
    databaseColumnName: 'workMode',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Work Mode',
    description: 'Work Mode Table8-1',
  },
  A49: {
    address: '030F',
    databaseColumnName: 'temperature',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Temperature',
    description: 'Inverter internal temperature',
    unit: 'CELSIUS',
    times: 10,
  },
  A50: {
    address: '0310',
    databaseColumnName: 'errorMessageH',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Error Message H',
    description: 'Failure description for status "failure" Table8-2',
  },
  A51: {
    address: '0311',
    databaseColumnName: 'errorMessageL',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Error Message L',
    description: 'Failure description for status "failure" Table8-2',
  },
  A52: {
    address: '0312',
    databaseColumnName: 'eTotalH',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'E-Total H',
    description: 'Total Feed Energy to grid',
    unit: 'KILOWATT_HOUR',
    times: 10,
  },
  A53: {
    address: '0313',
    databaseColumnName: 'eTotalL',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'E-Total L',
    description: 'Total Feed Energy to grid',
    unit: 'KILOWATT_HOUR',
    times: 10,
  },
  A54: {
    address: '0314',
    databaseColumnName: 'hTotalH',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'h-Total H',
    description: 'Total feeding hours',
    unit: 'HOUR',
  },
  A55: {
    address: '0315',
    databaseColumnName: 'hTotalL',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'h-Total L',
    description: 'Total feeding hours',
    unit: 'HOUR',
  },
  A56: {
    address: '0316',
    databaseColumnName: 'firmwareVersion',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Firmware Version',
  },
  A57: {
    address: '0317',
    databaseColumnName: 'warningCode',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Warning Code',
  },
  A58: {
    address: '0318',
    databaseColumnName: 'pv2FaultValue',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'PV2FaultValue',
    description: 'PV2 voltage fault value',
    unit: 'VOLT',
    times: 10,
  },
  A59: {
    address: '0319',
    databaseColumnName: 'functionsValue',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Functions Value',
    description: 'Table 8-3',
  },
  A60: {
    address: '031A',
    databaseColumnName: 'line2VfaultValue',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Line2VfaultValue',
    description: 'Phase L2 voltage fault value',
    unit: 'VOLT',
    times: 10,
  },
  A61: {
    address: '031B',
    databaseColumnName: 'line3VfaultValue',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Line3VfaultValue',
    description: 'Phase L3 voltage fault value',
    unit: 'VOLT',
    times: 10,
  },
  A62: {
    address: '031C',
    databaseColumnName: 'busVoltage',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'BUSVoltage',
    unit: 'VOLT',
    times: 10,
  },
  A63: {
    address: '031D',
    databaseColumnName: 'nbusVoltage',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'NBUSVoltage',
    unit: 'VOLT',
    times: 10,
  },
  A64: {
    address: '031E',
    databaseColumnName: 'line3FfaultValue',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Line3FfaultValue',
    description: 'Phase L3 frequency fault value',
    unit: 'HERTZ',
    times: 100,
  },
  A65: {
    address: '031F',
    databaseColumnName: 'safetyCountry',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Safety Country',
    description: 'GFCI check',
    unit: 'AMPERE',
    times: 1000,
  },
  A66: {
    address: '0320',
    databaseColumnName: 'eFeedDay',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'E-Day',
    description: 'Feed Engery to grid in today',
    unit: 'KILOWATT_HOUR',
    times: 10,
  },
  A67: {
    address: '033B',
    databaseColumnName: 'yearMonth',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Year :Month',
    description: 'High byte :Year; Low byte:Month',
  },
  A68: {
    address: '033C',
    databaseColumnName: 'dateHour',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Date :Hour',
    description: 'High byte :Date; Low byte:Hour',
  },
  A69: {
    address: '033D',
    databaseColumnName: 'minuteSecond',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Minute :Second',
    description: 'High byte :Minute; low byte:Second',
  },
  A70: {
    address: '033E',
    databaseColumnName: 'manufactureID',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Manufacture ID',
    description: 'Manufacturer Identifier for Hanneng',
  },
  A71: {
    address: '033F',
    databaseColumnName: 'rssi',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'RSSI',
    description: 'Strength of Signal (WiFi/GPRS 有效)',
    unit: 'PERCENTAGE',
  },
  A72: {
    address: '0340',
    databaseColumnName: 'pvMode',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'PV mode',
    description: 'HighByte:PV2; LowByte:PV1 Refer to Table 8-4',
  },
  A73: {
    address: '0354',
    databaseColumnName: 'fmVersionOfARM',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'FM version of ARM',
    description: 'Firmware Version of ARM',
  },
  A74: {
    address: '0355',
    databaseColumnName: 'gprsBurnInMode',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'GPRS Burn-in Mode',
    description: '0x00: normal mode 0x01: burn-in mode',
  },
  A75: {
    address: '0356',
    databaseColumnName: 'pacH',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Pac H',
    description: 'High Byte of Feeding power',
    unit: 'WATT',
  },
  A76: {
    address: '0357',
    databaseColumnName: 'vpv3',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Vpv3',
    description: 'PV3 voltage',
    unit: 'VOLT',
    times: 10,
  },
  A77: {
    address: '0358',
    databaseColumnName: 'vpv4',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Vpv4',
    description: 'PV4 voltage',
    unit: 'VOLT',
    times: 10,
  },
  A78: {
    address: '0359',
    databaseColumnName: 'ipv3',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Ipv3',
    description: 'PV3 current',
    unit: 'AMPERE',
    times: 10,
  },
  A79: {
    address: '035A',
    databaseColumnName: 'ipv4',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Ipv4',
    description: 'PV4 current',
    unit: 'AMPERE',
    times: 10,
  },
  A80: {
    address: '035B',
    databaseColumnName: 'istr1',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr1',
    description: 'PV String1 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A81: {
    address: '035C',
    databaseColumnName: 'istr2',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr2',
    description: 'PV String2 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A82: {
    address: '035D',
    databaseColumnName: 'istr3',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr3',
    description: 'PV String3 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A83: {
    address: '035E',
    databaseColumnName: 'istr4',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr4',
    description: 'PV String4 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A84: {
    address: '035F',
    databaseColumnName: 'istr5',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr5',
    description: 'PV String5 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A85: {
    address: '0360',
    databaseColumnName: 'istr6',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr6',
    description: 'PV String6 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A86: {
    address: '0361',
    databaseColumnName: 'istr7',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr7',
    description: 'PV String7 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A87: {
    address: '0362',
    databaseColumnName: 'istr8',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr8',
    description: 'PV String8 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A88: {
    address: '0363',
    databaseColumnName: 'istr9',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr9',
    description: 'PV String9 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A89: {
    address: '0364',
    databaseColumnName: 'istr10',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr10',
    description: 'PV String10 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A90: {
    address: '0365',
    databaseColumnName: 'istr11',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr11',
    description: 'PV String11 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A91: {
    address: '0366',
    databaseColumnName: 'istr12',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr12',
    description: 'PV String12 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A92: {
    address: '0367',
    databaseColumnName: 'istr13',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr13',
    description: 'PV String13 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A93: {
    address: '0368',
    databaseColumnName: 'istr14',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr14',
    description: 'PV String14 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A94: {
    address: '0369',
    databaseColumnName: 'istr15',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr15',
    description: 'PV String15 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A95: {
    address: '036A',
    databaseColumnName: 'istr16',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr16',
    description: 'PV String16 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A96: {
    address: '036B',
    databaseColumnName: 'iStringStatus',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istring Status',
    description: 'Table 8-5',
  },
  A97: {
    address: '036C',
    databaseColumnName: 'istr18',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr18',
    description: 'PV String18 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A98: {
    address: '036D',
    databaseColumnName: 'istr19',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr19',
    description: 'PV String19 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A99: {
    address: '036E',
    databaseColumnName: 'istr20',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'Istr20',
    description: 'PV String20 Current',
    unit: 'AMPERE',
    times: 10,
  },
  A100: {
    address: '036F',
    databaseColumnName: 'pidWietapStatus',
    functionCode: '03',
    functionOperationTypes: 'r',
    variableName: 'PID&Wietap Status',
    description: 'Table 8-6',
  },
};
